### PR TITLE
ACM-3043 ingress class annotation deprecated

### PR DESCRIPTION
**Pull request by KevinFCormier**
use spec.ingressClassName

Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@JakobGray Will this get picked up automatically for 2.6.5? Otherwise, can you kick the process that updates Helm charts after this merges? Thanks.

**Review by JakobGray — APPROVED** [review]
It should pick it up within 24 hours. I'll keep a watch to make sure.

**Pull request merged**
